version: 1
metadata:
  authors: "Jiacheng Jiang"
builder:
  configs:
    - platform: ios
      scheme: LucideSwift
      documentation_targets: ["LucideSwift"]
    - platform: macos-spm
      scheme: LucideSwift
      documentation_targets: ["LucideSwift"]
    - platform: tvos
      scheme: LucideSwift
      documentation_targets: ["LucideSwift"]
    - platform: watchos
      scheme: LucideSwift
      documentation_targets: ["LucideSwift"]
    - platform: visionos
      scheme: LucideSwift
      documentation_targets: ["LucideSwift"]
