//
//  Lucide.swift
//  LucideSwift
//
//  Auto-generated type-safe enum for all Lucide icons
//  This file is generated by the LucideGenerator tool
//  Do not edit manually
//

import SwiftUI

/// A Shape representing a Lucide icon
public struct LucideIconShape: Shape {
    let pathData: String
    
    public init(path: String) {
        self.pathData = path
    }
    
    public func path(in rect: CGRect) -> Path {
        var path = Path()
        
        // Parse SVG path data and convert to Swift Path
        let commands = SVGPathParser.parse(pathData: pathData)
        
        for command in commands {
            switch command.type {
            case .moveTo:
                if let x = command.values[safe: 0], let y = command.values[safe: 1] {
                    let point = normalizedPoint(x: x, y: y, in: rect)
                    path.move(to: point)
                }
                
            case .lineTo:
                if let x = command.values[safe: 0], let y = command.values[safe: 1] {
                    let point = normalizedPoint(x: x, y: y, in: rect)
                    path.addLine(to: point)
                }
                
            case .curveTo:
                if command.values.count >= 6 {
                    let cp1 = normalizedPoint(x: command.values[0], y: command.values[1], in: rect)
                    let cp2 = normalizedPoint(x: command.values[2], y: command.values[3], in: rect)
                    let end = normalizedPoint(x: command.values[4], y: command.values[5], in: rect)
                    path.addCurve(to: end, control1: cp1, control2: cp2)
                }
                
            case .closePath:
                path.closeSubpath()
            }
        }
        
        return path
    }
    
    private func normalizedPoint(x: CGFloat, y: CGFloat, in rect: CGRect) -> CGPoint {
        // Lucide icons are 24x24, normalize to rect
        let scaleX = rect.width / 24
        let scaleY = rect.height / 24
        return CGPoint(
            x: rect.minX + x * scaleX,
            y: rect.minY + y * scaleY
        )
    }
}

/// Type-safe access to all Lucide icons
public struct Lucide {
    // This will be auto-populated by the generator
    // Example entries (will be replaced by generator):
    
    /// Home icon
    public static var home: LucideIconShape {
        LucideIconShape(
            path: "M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"
        )
    }
    
    /// Settings icon
    public static var settings: LucideIconShape {
        LucideIconShape(
            path: "M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.09a2 2 0 0 1-1-1.72v-.51a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"
        )
    }
    
    /// Heart icon
    public static var heart: LucideIconShape {
        LucideIconShape(
            path: "M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"
        )
    }
    
    /// Star icon
    public static var star: LucideIconShape {
        LucideIconShape(
            path: "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z"
        )
    }
    
    /// Circle icon
    public static var circle: LucideIconShape {
        LucideIconShape(
            path: "M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"
        )
    }
}

// Array extension for safe access
private extension Array {
    subscript(safe index: Int) -> Element? {
        return indices.contains(index) ? self[index] : nil
    }
}
